### PR TITLE
127: fix Baseline setup in Mylyn.setup

### PR DESCRIPTION
**Pull request by BeckerFrank**
I did not include the APIBaselineFromTargetTask in the last commit so the Baseline was not really set.

### CODE REVIEW

**Review by ruspl-afed — COMMENTED** [review]
I'm not sure. How the addition should work with https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/146/files#diff-990c1078e104ec92925ec088de16bfb0fd0a93ff3313df71d28795d5ccca33e9R82 ?

**Comment by BeckerFrank** [comment]
> I'm not sure. How the addition should work with https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/146/files#diff-990c1078e104ec92925ec088de16bfb0fd0a93ff3313df71d28795d5ccca33e9R82 ?

The new way to set the API Baseline is a two step.
1) define the target "Mylyn Modular Target for API"
2)  Define a Setup Task that use the newly defined target

2) was the missing Task. I can publish a new Version where I give  the new setup an ID and check if we use this as a predecessor for other tasks.

**Comment by merks** [comment]
I think this is done.

**Review by ruspl-afed — APPROVED** [review]
Looks good

**Pull request merged**
