### PR TITLE
issue #17: Drop Trac Connector

### PR DESCRIPTION
**Pull request by BeckerFrank**
For now we do not delete the trac projects we only not import them into the workspace.

### CODE REVIEW

**Review by wimjongman — APPROVED** [review]

**Review by ruspl-afed — APPROVED** [review]
Well, I know people who still use trac.
But let's say they will have a starting point in a case of an irresistible desire to restore trac support

**Comment by BeckerFrank** [comment]
> Well, I know people who still use trac.
> But let's say they will have a starting point in a case of an irresistible desire to restore trac support

Should we instead of the remove make Trac a extra installable feature?

**Comment by wimjongman** [comment]
Task integrations are an important attractor. If people still use it, why drop it?

**Comment by wimjongman** [comment]
> > Well, I know people who still use trac.
> > But let's say they will have a starting point in a case of an irresistible desire to restore trac support
> 
> Should we instead of the remove make Trac a extra installable feature?

Yes. Good idea. We can do the same for other integrations. Like Github.

**Comment by BeckerFrank** [comment]
We continue this with pull request #42

**Pull request closed without merging**
