### PR TITLE
format all source files

### PR DESCRIPTION
**Pull request by BeckerFrank**
(see https://github.com/eclipse-mylyn/org.eclipse.mylyn.commons/issues/18)

### CODE REVIEW

**Review by ruspl-afed — COMMENTED** [review]
It will take time

**Comment by BeckerFrank** [comment]
> It will take time

Yes, no problem.
I select all projects and the execute Source -> Format so there no individual changes.

**Review by ruspl-afed — APPROVED** [review]
LGTM

**Comment by wimjongman** [comment]
Should we also run a source cleanup and not only a source format?

**Pull request merged**
