### PR TITLE
Prepare releng for 4.4.0

### PR DESCRIPTION
**Pull request by BeckerFrank**

### CODE REVIEW

**Review by merks — APPROVED** [review]
Mass version changes are hard to review.  😝

**Comment by BeckerFrank** [comment]
> Mass version changes are hard to review. 😝

Yes, but if you also have to change the versions for dependencies, it becomes even more difficult.
Maybe we can change some places to work with ranges instead of a fixed version.
Example: bundle-version="[4.4.0,5.0.0)" instead of bundle-version="4.4.0" in the *.MF files

Should I make this change?

**Comment by merks** [comment]
FYI the hamcrest issue this is a glitch.

Yes, I approved the changes.

**Pull request merged**
