### PR TITLE
Import of the EGit GitHub connector

### PR DESCRIPTION
**Pull request by wimjongman**

### CODE REVIEW

**Review by ruspl-afed — COMMENTED** [review]
Do you plan to build and publish p2 repo for this component together with others @wimjongman ? In this case pom manifest will require changes.
I would say these changes are required before merge because current CI does not even try to build newly added units.

**Comment by BeckerFrank** [comment]
I have checkout the branch github and local fix the compile errors by update the mockito version and change the egit Version from 6.4 to 6.2.

Should I push my changes to this branch?

**Comment by wimjongman** [comment]
Yes sure! Thanks.

**Comment by wimjongman** [comment]
> I have checkout the branch github and local fix the compile errors by update the mockito version and change the egit Version from 6.4 to 6.2.
> 
> Should I push my changes to this branch?

@BeckerFrank I have to do this run again. See comment https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/18

**Comment by BeckerFrank** [comment]
> > I have checkout the branch github and local fix the compile errors by update the mockito version and change the egit Version from 6.4 to 6.2.
> > Should I push my changes to this branch?
> 
> @BeckerFrank I have to do this run again. See comment #18

@wimjongman: Can we place put the GitHub Connector into org.eclipse.mylyn/mylyn.tasks/connectors/github after we have merged Pull Request #42. I did not import org.eclipse.egit.github.core so I hope that it is no problem to redo my work after this.

**Comment by wimjongman** [comment]
Sure!

**Comment by wimjongman** [comment]
We are also importing Egit support, which Egit has dropped. I will also put this in the 'connectors' category, although it is focused on other aspects.

**Comment by gnl42** [comment]
@BeckerFrank Where can I find your branch?

**Comment by BeckerFrank** [comment]
> @BeckerFrank Where can I find your branch?

We have the two branches github and github_2 but in both we have errors because we can not add org.eclipse.egit.github.core to the target platform

**Comment by BeckerFrank** [comment]
Ask in https://bugs.eclipse.org/bugs/show_bug.cgi?id=454237 if we can have the org.eclipse.egit.github.core as a separate jar / feature so that we can remove the workaround.

**Comment by ruspl-afed** [comment]
> Ask in https://bugs.eclipse.org/bugs/show_bug.cgi?id=454237 if we can have the org.eclipse.egit.github.core as a separate jar / feature so that we can remove the workaround.

Do you think this one could be sufficient https://mvnrepository.com/artifact/org.eclipse.mylyn.github/org.eclipse.egit.github.core?

**Comment by BeckerFrank** [comment]
> > Ask in https://bugs.eclipse.org/bugs/show_bug.cgi?id=454237 if we can have the org.eclipse.egit.github.core as a separate jar / feature so that we can remove the workaround.
> 
> Do you think this one could be sufficient https://mvnrepository.com/artifact/org.eclipse.mylyn.github/org.eclipse.egit.github.core?

Yes that was what I was looking for!
I update this branch and remove the workaround.

**Comment by BeckerFrank** [comment]
I think we can close this and continue with https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/56

**Comment by BeckerFrank** [comment]
@wimjongman: If you think we still need this please reopen it.

**Comment by wimjongman** [comment]
Thanks for the cleanup Frank.

**Pull request closed without merging**
