### PR TITLE
[#347] adjust the OOMPH setup

### PR DESCRIPTION
**Pull request by BeckerFrank**
To continue with  issue #315 we have to adjust the Mylyn.setup to the changes from #347

### CODE REVIEW

**Comment by ruspl-afed** [comment]
But do we need these launches? Mylyn Docs bundles now have MANIFEST.MF

**Comment by BeckerFrank** [comment]
> But do we need these launches? Mylyn Docs bundles now have MANIFEST.MF

Yes we have the help project and the launcher "mylyn verify" creates the missing files.

**Comment by ruspl-afed** [comment]
Could you please point me on it? I'm asking to ensure that nothing was missed during conversion of maven packaging.

**Comment by ruspl-afed** [comment]
In other words: is this necessary for installer to call the complete maven build for the whole repository?

**Comment by ruspl-afed** [comment]
Thank you for the explanation, now I see. 
So we need to find a way how to build this only module instead of running the whole build.

**Review by ruspl-afed — APPROVED** [review]
Since it is checked on your side I think it is good to go.
However, reducing the scope of initial build could be a significant improvement.

**Comment by BeckerFrank** [comment]
> Since it is checked on your side I think it is good to go. However, reducing the scope of initial build could be a significant improvement.

Yes, I can try if I find a better way starting mid of next week.

**Pull request merged**
