### PR TITLE
refactor Task Connector locations

### PR DESCRIPTION
**Pull request by BeckerFrank**
Most files are only moved to new location, only some have changes!

### CODE REVIEW

**Review by ruspl-afed — APPROVED** [review]
To be honest I'm not a fan of deep hierarchical structures, but perhaps you have some clear picture in mind regarding where do we go in terms of repository layout.

**Review by wimjongman — APPROVED** [review]
Looks good to me. Let's go.

**Comment by mjmeijer** [comment]
Where has the bugzilla connector gone? Trac is now optional, but Bugzilla has disappeared

**Comment by BeckerFrank** [comment]
No Bugzilla is installed per Default and so we do not have an option but it is available.
Why do you think it is gone?
What url did you use?

**Comment by mjmeijer** [comment]
Trying from the staging URL but install fails, will post details tomorrow

**Comment by BeckerFrank** [comment]
Sorry wrong Information Here we have the Bugzilla Connector.
image
and same for https://download.eclipse.org/mylyn/stage/latest/

**Pull request merged**
