### PR TITLE
[#187] Align target content with SimRel 2023-06

### PR DESCRIPTION
**Pull request by ruspl-afed**
Provide and use mylyn-e4.28.target with content aligned with SimRel 2023-06

### CODE REVIEW

**Comment by ruspl-afed** [comment]
Ed @merks, this is what I plan to merge after #191

**Review by BeckerFrank — APPROVED** [review]
LGTM

**Comment by ruspl-afed** [comment]
Thank you for review @BeckerFrank !

**Comment by merks** [comment]
Note that https://download.eclipse.org/eclipse/updates/4.28-I-builds/ will disappear very shortly after the release date.

**Comment by ruspl-afed** [comment]
I know. But what is an alternative?

**Comment by merks** [comment]
There isn't an alternative until they promote the release to appear under 

https://download.eclipse.org/eclipse/updates/4.28/ 

It's just an observation that we'll want to revisit this right after the release.  I always run into multiple broken builds right after the release too.  😱

**Comment by ruspl-afed** [comment]
> I always run into multiple broken builds right after the release too. 😱

I feel your pain

**Pull request merged**
