### PR TITLE
Ensure EGit/JGit 7.x is in the permitted version range

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@BeckerFrank  @ruspl-afed 

EGit/JGit will move to a 7.x version so we need to be sure that works with Mylyn:

https://github.com/eclipse-simrel/simrel.build/pull/458

**Comment by ruspl-afed** [comment]
Thank you for creating this PR @merks , let's wait if Mylyn can compile with EGit 7

**Comment by merks** [comment]
Yes, I've marked it as a draft that that is doesn't get merged, i.e., I don't want to make this specific target platform change permanent.

**Comment by merks** [comment]
Note the build worked:

image

I'll revert the target platform change.

**Comment by merks** [comment]
@ruspl-afed 

I think we could merge this.  OK?

If there is a new build, I can test that EGit and Mylyn work together in SimRel...

**Review by ruspl-afed — APPROVED** [review]
LGTM

**Pull request merged**
