### PR TITLE
Provide an Oomph configuration for .github/blob/main/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@BeckerFrank  

This is needed for use on the contributing page:

https://github.com/eclipse-mylyn/.github/blob/main/CONTRIBUTING.md

I can't fully test it until it's committed and then this job runs and will create a specialized badge for Mylyn.

https://ci.eclipse.org/oomph/job/setup-archiver/

**Comment by BeckerFrank** [comment]
> @BeckerFrank
> 
> This is needed for use on the contributing page:
> 
> https://github.com/eclipse-mylyn/.github/blob/main/CONTRIBUTING.md
> 
> I can't fully test it until it's committed and then this job runs and will create a specialized badge for Mylyn.
> 
> https://ci.eclipse.org/oomph/job/setup-archiver/

Thank you
for fixing the problem that was my error. I have not tested the link, my test was via the installer application with selecting Mylyn.

**Comment by wimjongman** [comment]
I tried the installer, but it failed in the end:

image

<details><summary>Stacktrace</summary>

```

Performing Launch submodulConfig
Execute Debug Command
ERROR: org.eclipse.debug.core code=125 Exception occurred executing command line.
java.io.IOException: Cannot run program "C:\Apps\eclipse\oomph\mylyn-master\git\org.eclipse.mylyn.all\org.eclipse.mylyn\org.eclipse.mylyn.releng\bin\submodulConfig.sh" (in directory "C:\apps\eclipse\oomph\mylyn-master\git\org.eclipse.mylyn.all"): CreateProcess error=193, %1 is not a valid Win32 application
  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
  at java.base/java.lang.Runtime.exec(Runtime.java:615)
  at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:970)
  at org.eclipse.core.externaltools.internal.launchConfigurations.ProgramLaunchDelegate.launch(ProgramLaunchDelegate.java:103)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:806)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:717)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:712)
  at org.eclipse.oomph.setup.launching.impl.LaunchTaskImpl.perform(LaunchTaskImpl.java:341)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
  at java.base/java.lang.ProcessImpl.create(Native Method)
  at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
  at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
  at java.base/java.lang.Runtime.exec(Runtime.java:615)
  at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:970)
  at org.eclipse.core.externaltools.internal.launchConfigurations.ProgramLaunchDelegate.launch(ProgramLaunchDelegate.java:103)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:806)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:717)
  at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:712)
  at org.eclipse.oomph.setup.launching.impl.LaunchTaskImpl.perform(LaunchTaskImpl.java:341)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  ... 1 more

Took 177 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```
</details>

**Comment by BeckerFrank** [comment]
Ups!

My fault the Task submoduleConfig is a Linux / MacOS task and I did not set a filter for the Platform and did not implement a Windows cmd version.

But with https://github.com/eclipse-mylyn/.github/issues/15 we no longer have the https://github.com/eclipse-mylyn/org.eclipse.mylyn.all Repository with submodules

For now, skip the Task submoduleConfig.

Frank

**Pull request merged**
