### PR TITLE
[#167] Many "Not properly disposed SWT resource" in error log

### PR DESCRIPTION
**Pull request by ruspl-afed**
Move resource image resource tracking from `ConnectorDescriptorItemUi` to enclosing `DiscoveryViewer`

Fixes https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/167

### CODE REVIEW

**Review by wimjongman — COMMENTED** [review]
I think you found the bug in the clearDisposables method where the disposables were cleared without being disposed of.  That was fixed. I don't get why this has to be such a big change.

There are a lot of changes in this class which are very hard to review without actually stepping through the code. Especially the modern way of using chained methods of a class instead of actual Java statements is hard to grasp.

It looks like you have replaced the "disposables" cache with an "images" cache. Is that correct?

**Comment by ruspl-afed** [comment]
> I don't get why this has to be such a big change

it does not look big to me, but I may try to minimize it to the base minimum. I thought to divide it into several PRs, but in this case there is a risk that the review process will take several times longer.

> Especially the modern way of using chained methods of a class instead of actual Java statements is hard to grasp.

Well, it was never required to avoid modern Java API and prefer deeply nested `if ( x != null && x.y() != null )` blocks instead.

> It looks like you have replaced the "disposables" cache with an "images" cache. Is that correct?

Not exactly. `ImageRegistry` is used for images only, because they have natural mapping to URL and can be reused, since they have, while Fonts and other SWT resources.

**Review by wimjongman — APPROVED** [review]
Ok, thanks for the clarification. Let's take this as you have designed it without further rework.

**Comment by ruspl-afed** [comment]
Thank you for review @wimjongman !

**Pull request merged**
