### PR TITLE
issue #17: Trac Connector should be a installable feature

### PR DESCRIPTION
**Pull request by BeckerFrank**
I also have refactor the other connectors into a new folder.

### CODE REVIEW

**Comment by ruspl-afed** [comment]
@BeckerFrank do you need help to fix maven build?

**Comment by BeckerFrank** [comment]
> @BeckerFrank do you need help to fix maven build?

Yes, my local clean install works but license check got errors.
I do not know why.

**Comment by ruspl-afed** [comment]
> Yes, my local clean install works

Strange, since `continuous-integration/jenkins/pr-merge` fails

**Comment by BeckerFrank** [comment]
> > Yes, my local clean install works
> 
> Strange, since `continuous-integration/jenkins/pr-merge` fails

I run this from Eclipse with 
image
because of test failures.
Can you checkout and local build the branch on your environment?

**Comment by ruspl-afed** [comment]
Sorry @BeckerFrank was no time to check on my side. But you have already found and fixed the issue with pom.xml, great!

However, I still don't understand the following:
1) How Bugzilla is related with Trac? There are lot of moves of bugzilla files in this PR.
2) How these changes address the statement in the title "Trac Connector should be an installable feature"? I can see a lot of restructuring for `category.xml` but Trac support is still in the category `org.eclipse.mylyn.integrations.category` with all the others.
Perhaps, you mean something different by "installable feature".

**Comment by BeckerFrank** [comment]
> Sorry @BeckerFrank was no time to check on my side. But you have already found and fixed the issue with pom.xml, great!
> 
> However, I still don't understand the following:
> 
> 1. How Bugzilla is related with Trac? There are lot of moves of bugzilla files in this PR.
I want to move all the task Connectors in a new location (connectors) and also group the plugins. So we now have 
connectors/bugzilla, connectors/bugzilla-rest and connectors/trac for the 3 task connectors included in org.eclipse.mylyn. In the future we will have connectors/github and maybe connectors/gitlab as the two new supported Connectors.
> 2. How these changes address the statement in the title "Trac Connector should be an installable feature"? I can see a lot of restructuring for `category.xml` but Trac support is still in the category `org.eclipse.mylyn.integrations.category` with all the others.
Actual you get the bugzilla and trac as standard. New is that you must select trac to install the connector.
Bildschirm­foto 2023-01-26 um 06 21 43
>    Perhaps, you mean something different by "installable feature".

How can we fix the error with the Licenses?
[INFO] License information could not be automatically verified for the following content:
[3229](https://github.com/eclipse-mylyn/org.eclipse.mylyn/actions/runs/4003097483/jobs/6870906474#step:9:3231)
[INFO] 
[3230](https://github.com/eclipse-mylyn/org.eclipse.mylyn/actions/runs/4003097483/jobs/6870906474#step:9:3232)
[INFO] p2/orbit/p2.eclipse.plugin/org.tigris.subversion.clientadapter/1.8.6
[3231](https://github.com/eclipse-mylyn/org.eclipse.mylyn/actions/runs/4003097483/jobs/6870906474#step:9:3233)
[INFO] p2/orbit/p2.eclipse.plugin/org.tigris.subversion.subclipse.core/1.8.22
[3232](https://github.com/eclipse-mylyn/org.eclipse.mylyn/actions/runs/4003097483/jobs/6870906474#step:9:3234)

**Comment by ruspl-afed** [comment]
Thank you for explanation @BeckerFrank 

> How can we fix the error with the Licenses?

We need to use Dash to request an IP team verdict for these dependencies. I planned to do this several days ago, but I still can't recover from some sticky flu.

**Comment by BeckerFrank** [comment]
@ruspl-afed, @wimjongman: after merge the main Branch we can continue with the review!

**Comment by BeckerFrank** [comment]
We have fixed the license problem with a merge of the main branch into this pull request.
Can we continue?

**Review by wimjongman — APPROVED** [review]
I can't review 719 files Frank. If you say go then go.

**Comment by BeckerFrank** [comment]
> I can't review 719 files Frank. If you say go then go.

Should we split this in two reviews?

- Trac as installable feature
- refactor (move trac and bugzilla connetors to new location) later we can put the GitHub Connector in the same folder.

**Comment by wimjongman** [comment]
Let's just get this in and solve issues later.

**Comment by wimjongman** [comment]
Did I not already push the github connector to the correct directory in github_2?

**Comment by BeckerFrank** [comment]
we continue this in https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/58

**Pull request closed without merging**
