### PR TITLE
change repository url to 4.33 final (#611)

### PR DESCRIPTION
**Pull request by BeckerFrank**

### CODE REVIEW

**Comment by wimjongman** [comment]
This repo does not look like it is a final name. @merks WDYT?

**Review by ruspl-afed — APPROVED** [review]
For me it does. It has "R-" prefix. May be you are referring to a composite that sounds like "2024-09" @wimjongman  but we prefer to use precise p2 URLs for better dependency control.

**Comment by merks** [comment]
> This repo does not look like it is a final name. @merks WDYT?

In the Oomph setups we even associate a variable with each Platform SDK repository so that one can more easily reuse the URLs:

image

So definitely the one used in this PR is final.

**Comment by wimjongman** [comment]
Thanks for verifying,

**Pull request merged**
