### PR TITLE
[#462] Switch to Tycho 4.0.6

### PR DESCRIPTION
**Pull request by ruspl-afed**
* switch from 4.0.4 to 4.0.6
* resolve version warnings

### CODE REVIEW

**Comment by ruspl-afed** [comment]
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4382

**Comment by ruspl-afed** [comment]
@akurtakov these reviews was already requested earlier, and were processed, you can see them earlier in comments

Where should we submit issues like this @waynebeaton ?

**Comment by akurtakov** [comment]
Well, they seem to not have been processed proper as licensecheck still fails.

**Comment by merks** [comment]
Note that the two "duplicates" are actually different issues (different numbers) with the same title and both were closed as "project content" so some database appears not to be correctly updates to avoid creating a duplicate.

**Comment by ruspl-afed** [comment]
> Note that the two "duplicates" are actually different issues (different numbers) with the same title and both were closed as "project content" so some database appears not to be correctly updates to avoid creating a duplicate.

This is what I tried to say, thank you @merks for more detailed explanation

**Comment by merks** [comment]
@waynebeaton 

So while these two issues are open, dash does not created duplicates. 

These are the two pairs.

ch.ethz.iks.slp/1.4.1.v20230528-2254

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13507
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13852

ch.ethz.iks.r_osgi.remote/1.3.0.v20231021-2015

- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13509
- https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13854

**Comment by waynebeaton** [comment]
The `ch.ethz.iks.slp` bundles are, to the best of my knowledge, project code from the Eclipse Communication Framework, and are distributed under the EPL-2.0. Getting the Dash/IPLab to understand all of these different associations has been a game of whack-a-mole. I'll update the system to recognise this as project code.

In the meantime, there is no requirement that the Eclipse Dash License Tool be 100% happy with the information that you feed it (rather, Eclipse Dash is a tool that is intended to help committers engage in the IP due diligence process, and some amount of committer judgement is expected).

**Comment by ruspl-afed** [comment]
> In the meantime, there is no requirement that the Eclipse Dash License Tool be 100% happy with the information that you feed it (rather, Eclipse Dash is a tool that is intended to help committers engage in the IP due diligence process, and some amount of committer judgement is expected).

Yes, this is clear. And thank you so much @waynebeaton for providing this tool, it really saves hours and days per every project cycle.
My question is: when something is wrong with Eclipse Dash, like in this PR, what is the preferred way to report the issue?

**Comment by merks** [comment]
Collectively we all really **love** ❤️  💟  😍 dash and really rely on it.   While there may be no requirement that dash be completely happy, when it's not happy, it's a little bit like having a project with warnings.  Once you start to ignore, one warning, then two warning then eventually you have a project with so many warnings you don't noticed when there is a new one...

For Orbit I have to accept that I need to do builds for things for which license reviews are pending so my build keep track of which those are:

https://ci.eclipse.org/orbit/job/orbit-simrel-maven-osgi/lastBuild/

**Comment by waynebeaton** [comment]
> My question is: when something is wrong with Eclipse Dash, like in this PR, what is the preferred way to report the issue?

@ruspl-afed Under normal circumstances, when the IP Team gets an issue like these that they don't understand, they work with me to resolve and we're very often able to sort out these connections without the committers even knowing that anything special has happened. Looping me in as a means of escalating seems to also work :-)

@merks I understand. It's actually very gratifying that expectations are so high. Every time we deal with one of these corner cases, the coverage gets a little better.

**Pull request merged**
