### PR TITLE
RepositoryLocationPart doesn't accept "http://" as a valid URL #45

### PR DESCRIPTION
**Pull request by gnl42**

### CODE REVIEW

**Comment by BeckerFrank** [comment]
Good catch!
This is a regression from a unintended change in Commit cd68250fa1680a934616fb291c84c8d5e6abd4be (10 weeks ago)

**Review by BeckerFrank — APPROVED** [review]
LGTM

**Review by ruspl-afed — APPROVED** [review]
Thanks!

**Comment by BeckerFrank** [comment]
How do we fix the 3 license problems?
[INFO] maven/mavencentral/org.osgi/org.osgi.annotation.versioning/1.1.2
[3232](https://github.com/eclipse-mylyn/org.eclipse.mylyn/actions/runs/4058290192/jobs/6991050351#step:9:3234)
[INFO] p2/orbit/p2.eclipse.plugin/org.tigris.subversion.clientadapter/1.8.6
[3233](https://github.com/eclipse-mylyn/org.eclipse.mylyn/actions/runs/4058290192/jobs/6991050351#step:9:3235)
[INFO] p2/orbit/p2.eclipse.plugin/org.tigris.subversion.subclipse.core/1.8.22
[3234](https://github.com/eclipse-mylyn/org.eclipse.mylyn/actions/runs/4058290192/jobs/6991050351#step:9:3236)

**Comment by ruspl-afed** [comment]
> How do we fix the 3 license problems? [INFO] maven/mavencentral/org.osgi/org.osgi.annotation.versioning/1.1.2 [3232](https://github.com/eclipse-mylyn/org.eclipse.mylyn/actions/runs/4058290192/jobs/6991050351#step:9:3234) [INFO] p2/orbit/p2.eclipse.plugin/org.tigris.subversion.clientadapter/1.8.6 [3233](https://github.com/eclipse-mylyn/org.eclipse.mylyn/actions/runs/4058290192/jobs/6991050351#step:9:3235) [INFO] p2/orbit/p2.eclipse.plugin/org.tigris.subversion.subclipse.core/1.8.22 [3234](https://github.com/eclipse-mylyn/org.eclipse.mylyn/actions/runs/4058290192/jobs/6991050351#step:9:3236)

we need to merge https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/48 and then update this one from main branch @BeckerFrank

**Comment by BeckerFrank** [comment]
@gnl42: We had a License Problem with subclipse so we remove the plugin. Can you please merge the actual main with commit ID ae947f846e8a905b5da114809e9fa73a869e31f0 into your branch. This will fix the license problem so that we can approve nd merge your change.

Thanks in advance.

**Comment by gnl42** [comment]
@BeckerFrank Merged and pushed

**Review by wimjongman — APPROVED** [review]
LGTM!

**Comment by wimjongman** [comment]
Thanks, George!

**Pull request merged**
