### PR TITLE
[#182] Add required 3rd party bundles

### PR DESCRIPTION
**Pull request by ruspl-afed**
* reworked "org.apache.*" dependencies from `Require-Bundle` to `Import-Package`
* added missed bundle entries to `category.xml`

Rework of other dependencies like guava is planned for other PRs

### CODE REVIEW

**Comment by merks** [comment]
I'm not sure the plan here, but the cycle time for the testing will take way way too long.  Please have a look at

https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/241

**Comment by ruspl-afed** [comment]
I'll delay these changes, Ed @merks has quicker solution with #241

**Comment by ruspl-afed** [comment]
I plan to merge this one when pipeline will succeed Ed @merks

**Review by merks — APPROVED** [review]
Note that this issue is highly relevant:

https://github.com/eclipse-orbit/orbit-simrel/issues/1

There are lots of new versions of dependencies including new versions of lucene.

I want to get rid of this too:

https://github.com/eclipse-orbit/orbit/issues/48

But some Orbit things on which Mylyn depends still explicitly use it...

None of this speaks against your changes rather that further changes will be relevant.

**Pull request merged**
