### PR TITLE
[#301] update to Tycho 4.0.3

### PR DESCRIPTION
**Pull request by BeckerFrank**

### CODE REVIEW

**Comment by gnl42** [comment]
I gave it a quick try initially but gave up because the "Problems" view showed some 5/6 complaints about options not being valid and I had no idea what the alternatives would be.

**Comment by wimjongman** [comment]
> I gave it a quick try initially but gave up because the "Problems" view showed some 5/6 complaints about options not being valid and I had no idea what the alternatives would be.
> 

Can you attach the text behind the lines?

**Comment by gnl42** [comment]
image

**Comment by wimjongman** [comment]
I mean, if you double-click on a line, is there more information?

**Comment by BeckerFrank** [comment]
I think it's some kind of caching problem. I delete all warnings and then force a rebuild with Clean... after that I can't see the warnings anymore.
The warning appears again when I switch back to the main branch. The same fix works here as before.

**Comment by gnl42** [comment]
I guess you're right about it being some sort of caching problem.

When I noticed the warnings  I switched back to 3.0.3 and they went away. Now when I tried it they remained ???

I had a quick look at the official documentation for some of the plugins and the options are not listed. I guess they are remnants of the early days of the tycho plugins and can be removed

**Review by gnl42 — APPROVED** [review]
LGTM

**Pull request merged**
