### PR TITLE
small oomph setup fixes

### PR DESCRIPTION
**Pull request by BeckerFrank**
1. remove the not working .github repository setup
2. add all Doc projects to the Doc Workingset

### CODE REVIEW

**Comment by merks** [comment]
Instead of removing it, might it be better to fix it?

**Comment by BeckerFrank** [comment]
> Instead of removing it, might it be better to fix it? (I can help fix it.)

I do not really use / need the [.github](https://github.com/eclipse-mylyn/.github) repository. 

I get an java.lang.Exception: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /Users/frank/eclipse/mylyn-admin-test/git/.github

I think we have a git clone problem with repositories starting with a dot.

**Comment by merks** [comment]
Yes, they generally need a bit of special attention...  E.g., like this for simrel:

https://github.com/eclipse-simrel/simrel.build/blob/bcf05da46c2f46508118643655378420688296aa/SimRel.setup#L188-L192

So that it creates a folder simrel.github and not .github.  I can help make it work nicely if you wish...

**Comment by merks** [comment]
BTW, I also think this new build installer tasks does not need to run on each startup and there is a property to disable that...  It's a bit annoying to wait for a build each time you start the IDE...

**Comment by BeckerFrank** [comment]
> Yes, they generally need a bit of special attention... E.g., like this for simrel:
> 
> https://github.com/eclipse-simrel/simrel.build/blob/bcf05da46c2f46508118643655378420688296aa/SimRel.setup#L188-L192
> 
> So that it creates a folder simrel.github and not .github. I can help make it work nicely if you wish...

So the trick is to set the locationQualifier.  Right?

**Comment by BeckerFrank** [comment]
@merks: Please check if this is better now.

**Review by merks — APPROVED** [review]
It looks better.

Once it's committed I'll try another completely-from-scratch test run.

I'd suggest committing it without waiting for others to review because there's nothing really controversial, it has has no impact on the build, and I can fully test it better once it's committed.

**Review by ruspl-afed — APPROVED** [review]
LGTM

**Pull request merged**
