### PR TITLE
Exclude the Uncategorized category from the promoted update site

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
The promoted update site will only contain the categorized items like in this local build:

image

**Review by ruspl-afed — APPROVED** [review]
LGTM

**Comment by BeckerFrank** [comment]
> The promoted update site will only contain the categorized items like in this local build:
> 
@merks: how do you build this local in /org.eclipse.mylyn-site/updates/nightly ? I have used the one in target/repository but this includes the Uncategorized category.

**Comment by merks** [comment]
I have an external tools launch configuration for kicking off a Maven build:

image


I can even point it at a local repository of a locally build JustJ publisher, but you don't need that.

The important three parameters are selected, i.e., one to enable the profile and the other to specify where to publish the results; in this case in the site project, but not in the target folder because that folder is deleted each build but the site accumulates the results and I can test doing milestone and release builds.

**Pull request merged**
