### PR TITLE
Update guava, gson, and mockito

### PR DESCRIPTION
**Pull request by merks**
Fixes https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/159

### CODE REVIEW

**Comment by merks** [comment]
Note that upgrading to the latest guava only ran into to errors in tests, so I do think the APIs being used are stable.  Also the gson old version is causing duplicates in SimRel so that too needs and update.  The older version of mockito was kind of pointless because other tests are using the newer version already.  I'll need to force push because I overlooked the feature.xml use of mockito...

**Comment by merks** [comment]
It will be nice in the long terms to stop including 3rd party libraries in features because that locks in a specific version whereas all the actual bundle requirements are happy with a range of versions...

**Comment by akurtakov** [comment]
Thanks @merks ! Guava usage has been causing all kind of issues in many places so even standardizing on one version is quite helpful.

**Comment by ruspl-afed** [comment]
> It will be nice in the long terms to stop including 3rd party libraries

sure, and we are moving in this direction

**Comment by merks** [comment]
@ruspl-afed 

This is done.  I'd like to do the branding changes next...

**Review by ruspl-afed — APPROVED** [review]
Thank you Ed @merks

**Pull request merged**
