### PR TITLE
[#182] Take care of orphan bundles

### PR DESCRIPTION
**Pull request by ruspl-afed**
* Add orphan bundles to features
* Inline excessive features
* Restore Gerrit (let's remove it together with Bugzilla a bit later)

### CODE REVIEW

**Review by merks — APPROVED** [review]
Looks okay.

**Comment by merks** [comment]
Note that just because Eclipse doesn't use Bugzilla doesn't mean no one else does.  Similarly for Gerrit.  In fact I saw that EGit @msohn was asking to be hosted/migrated somewhere where they could continue to use Gerrit.

**Comment by merks** [comment]
@ruspl-afed 

Note that one can test what you're going to contribute to SimRel via the PR build result.  E.g., this other PR eventually produces and update site:

https://ci.eclipse.org/mylyn/job/GitHub-mylyn-Orga/job/org.eclipse.mylyn/view/change-requests/job/PR-197/lastSuccessfulBuild/artifact/org.eclipse.mylyn-site/target/repository/

You can use that to author your SimRel changes **before** doing a milestone build.

I can help with that, but I'm not 100% sure which exact features you plan to include.

**Comment by gnl42** [comment]
@ruspl-afed Do you have any more encompassing  changes in the works?

**Comment by ruspl-afed** [comment]
nope, please continue with Hudson->Jenkins repackaging. Since we have major version change everything may be renamed.

**Pull request merged**
