### PR TITLE
Remove wrong/unused/etc. maven plugin configurattions

### PR DESCRIPTION
**Pull request by akurtakov**

### CODE REVIEW

**Comment by merks** [comment]
It’s really great to see this activity. Kudos! 🥇

**Comment by akurtakov** [comment]
I enjoyed Mylyn a lot back in the bugzilla days. I really hope that same happens now with GH.

**Comment by ruspl-afed** [comment]
Thank you for your effort @akurtakov!

This is also very helpful to learn how maven plugin configuration should change to follow Tycho upgrades.

**Comment by akurtakov** [comment]
> Thank you for your effort @akurtakov!
> 
> This is also very helpful to learn how maven plugin configuration should change to follow Tycho upgrades.

One can use lemminx-maven via m2e pom.xml editor and it will warn you about non-supported configurations.

**Pull request merged**
