### PR TITLE
Remove guava in wikitext, Part 1 #521

### PR DESCRIPTION
**Pull request by gnl42**
Replace basic guava constructs with Java 17/Apache commons equivalents

### CODE REVIEW

**Comment by gnl42** [comment]
Can I merge this now, or should I wait for 4.3.0 to be released?

**Comment by BeckerFrank** [comment]
> Can I merge this now, or should I wait for 4.3.0 to be released?

I think it depends on how we handle https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/354 (also planned for 4.3).
For me it is Ok to merge this after resolving the conflicts.

**Comment by ruspl-afed** [comment]
Too risky for 4.3.0, we have not more than 3 days to produce final bits

**Comment by ruspl-afed** [comment]
Do you think we can remove unrelated changes from this PR @gnl42 ? There are a lot of changed line ends.

**Comment by gnl42** [comment]
Sigh, what are they doing back. I cleaned up all that.

Use  'Hide whitespace'

**Comment by gnl42** [comment]
Wrecken fracken. Just realized what I did. 
I removed them from the commit because they only had white space changes. I should have left them in because of the line ending update a while ago. 

I'll redo the merge

**Pull request closed without merging**
