### PR TITLE
Fix the build for main branch #10

### PR DESCRIPTION
**Pull request by ruspl-afed**
Deploy components individually for `main` branch

Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>

### CODE REVIEW

**Review by BeckerFrank — APPROVED** [review]
LGTM

But me maybe should create a new all nightly  snapshot repository and  retire the specific repositories after a parallel phase.

**Comment by ruspl-afed** [comment]
>  new all nightly snapshot repository and retire the specific repositories after a parallel phase

I was close to do that but at the last moment I found Mylyn Docs published sibling to Mylyn Commons and others.
What path do you have in mind @BeckerFrank for the new nightly location?

**Comment by wimjongman** [comment]
How about https://download.eclipse.org/mylyn/snapshots/nightly/

It already exists.

**Comment by ruspl-afed** [comment]
> How about https://download.eclipse.org/mylyn/snapshots/nightly/
> 
> It already exists.

Yes, it does, and it contains Mylyn Docs, I do not recommend to overlap with another project.
We can try to use subfolder like https://download.eclipse.org/mylyn/snapshots/nightly/all or something similar.

@akurtakov do you have any preference how to separate deploy locations for Mylyn Docs and Mylyn ?

**Comment by akurtakov** [comment]
Nope, these are just snapshots so if you say move mylyn-docs to x.y.z url we will just do it.

**Comment by wimjongman** [comment]
Why not? We can live next to docs.

../mylyn/snapshots/nightly/
     docs
     mylyn

**Comment by ruspl-afed** [comment]
> Why not? We can live next to docs.

ok, we can use https://download.eclipse.org/mylyn/snapshots/nightly/mylyn 

> these are just snapshots

true, and how do you see layout for milestones and releases?

**Comment by wimjongman** [comment]
I think like it is now:

          download.eclipse.org/mylyn/releases/${release}
                                          .../latest

docs can live here:

          download.eclipse.org/mylyn/docs/releases/${release}
                                               .../latest

Do we still need a composite repo?

**Pull request merged**
