### PR TITLE
[#37] Gitlab Connector Cleanup Code Style configuration for Java 17

### PR DESCRIPTION
**Pull request by BeckerFrank**
adjust the Source to the Codestyle from #200

### CODE REVIEW

**Comment by gnl42** [comment]
Looks like you already doing most of it by yourself :)

**Comment by BeckerFrank** [comment]
> Looks like you already doing most of it by yourself :)

I select the gitlab projects and the I select Source -> Format from the Context Menu.
Should I continue with committing this changes?

**Comment by gnl42** [comment]
Source->Clean Up... is a better approach

**Comment by gnl42** [comment]
LGTM

**Review by ruspl-afed — APPROVED** [review]
LGTM

**Review by gnl42 — APPROVED** [review]

**Pull request merged**
