### PR TITLE
Use JavaSE-17 #66

### PR DESCRIPTION
**Pull request by gnl42**
Switch to Java 17. Purely a brute force approach with checking.
Doesn't seem to introduce any new issues (current ones are still there for me).

Would be nice if Mylyn.setup could be updated to set the cleanup/save Eclipse preferences for Java 17, but I have no idea how to do that (yet).

### CODE REVIEW

**Comment by pdulth** [comment]
Hi, there is also the 1.8 to 17 occurences in **/.settings/org.eclipse.jdt.core.prefs i think

**Comment by wimjongman** [comment]
Java 17 support will be the first thing after 3.26.1

The reason is that Mylyn has been broken for a longer time. Moving to 17 would prevent everything pre-3.27 from consuming a working copy of Mylyn.

**Comment by BeckerFrank** [comment]
@gnl42: can you please update the branch so that we no longer have conflicts.

**Comment by gnl42** [comment]
It was easier to recreate the changes than trying to figure out what went wrong with the merge. 
Also a cleaner PR.

**Pull request closed without merging**
