### PR TITLE
[#150] Startup problems

### PR DESCRIPTION
**Pull request by ruspl-afed**
Move ActiveReviewManager startup to happen after `APP_STARTUP_COMPLETE`

Fixes https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/150

### CODE REVIEW

**Comment by ruspl-afed** [comment]
> That is a lot of code for such a small issue. Is it not easier to add a workbench listener?

Do you mean [this one](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/IWorkbenchListener.java)?

**Comment by wimjongman** [comment]
> > That is a lot of code for such a small issue. Is it not easier to add a workbench listener?
> 
> Do you mean [this one](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/IWorkbenchListener.java)?

Yes, then we are sure we are not too early 🤣 

I think we can just delete the code in the constructor since the window listener is already doing what the constructor does.

**Comment by wimjongman** [comment]
You see that the now commented code is the same code as seen in the window listener. I can't think why this would have to be done twice.

```
	private final IWindowListener windowListener = new IWindowListener() {

		public void windowOpened(IWorkbenchWindow window) {
		}

		public void windowDeactivated(IWorkbenchWindow window) {
			window.removePageListener(pageListener);
		}

		public void windowClosed(IWorkbenchWindow window) {
		}

		public void windowActivated(IWorkbenchWindow window) {
			window.addPageListener(pageListener);
			pageListener.pageActivated(window.getActivePage());
		}
	};

	public ActiveReviewManager() {
		PlatformUI.getWorkbench().addWindowListener(windowListener);
//		IWorkbenchWindow activeWorkbenchWindow = PlatformUI.getWorkbench().getActiveWorkbenchWindow();
//		if (activeWorkbenchWindow != null) {
//			activeWorkbenchWindow.addPageListener(pageListener);
//			windowListener.windowActivated(activeWorkbenchWindow);
//		}
	}
```

**Comment by ruspl-afed** [comment]
The problem is: we start to work with Workbench before its full startup (whatever it means). 
And, I know only one way to do this: listen for `APP_STARTUP_COMPLETE` event.

* I'm not sure when `AbstractUIPlugin#start` will be invoked, but most probably before the full Workbench initialization, just because in theory it could be a part of such initialization.
* Regarding `UIJob` - it will be launched in UI thread for sure, but I'm afraid there is no relation to Workbench state.

**Comment by ruspl-afed** [comment]
> That is a lot of code for such a small issue.

Hey, I added only a few lines of "code". 
All the rest is E4 magic, it is not considered! 😎

**Comment by BeckerFrank** [comment]
Maybe we can use something similar to BuildsStartup (interface org.eclipse.ui.IStartup).
Thoughts?

**Comment by ruspl-afed** [comment]
`IStartup` is a E2 way of what was done here with E4
It also will require a few lines of "code" and some changes for manifests.
And what will be the benefit?

**Comment by BeckerFrank** [comment]
> `IStartup` is a E2 way of what was done here with E4
> It also will require a few lines of "code" and some changes for manifests.
> And what will be the benefit?

I found that we have IStartup in 3 places and did not remember that this was the old way. Sorry :-(
Now I think we should remove the two unused cases and change  BuildsStartup (the only one with logic) to the E4 way.
Should I create a new Ticket?

**Comment by wimjongman** [comment]
> `IStartup` is a E2 way of what was done here with E4 It also will require a few lines of "code" and some changes for manifests. And what will be the benefit?

Yes, IStartup is not an option.

So the cause of the error is that display = null. The display is obviously not null when the UIjobs start running. 

I have tested the solution of https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/151#issuecomment-1554294145, and this works fine. So even though Alexander's solution is architecturally the best, I propose going for that simple solution.

**Comment by wimjongman** [comment]
> change BuildsStartup (the only one with logic) to the E4 way.
> Should I create a new Ticket?

When we have more use for an addon, then yes, we should implement that in favor of the IStartup solution.

**Comment by ruspl-afed** [comment]
> I have tested the solution of https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/151#issuecomment-1554294145, and this works fine. So even though Alexander's solution is architecturally the best, I propose going for that simple solution.

If you did so much work already @wimjongman , please propose your PR and we can close this one.

**Comment by ruspl-afed** [comment]
Well, it was modern and cool, but another solution wins.

**Pull request closed without merging**
