### PR TITLE
Get Maven dependencies needing a generated OSGi MANIFEST.MF centrally

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/103
https://github.com/eclipse-mylyn/.github/issues/23

### CODE REVIEW

**Comment by merks** [comment]
Note that when I ran the build that produced these artifacts

https://ci.eclipse.org/oomph/job/simrel/job/simrel-maven-bnd/4/console

it says this:

> [INFO] --- license-tool:0.0.1-SNAPSHOT:license-check (license-check) @ org.eclipse.oomph.maven-bnd.parent ---
> [INFO] Vetted license information was found for all content. No further investigation is required.
> [INFO] Summary file was written to: /home/jenkins/agent/workspace/simrel/simrel-maven-bnd/maven-bnd/target/dash/summary

So it's strange the that build didn't fail but this build failed...

I'm not sure I can do the /request-license-review thing...

**Comment by ruspl-afed** [comment]
> Can you please try posting a /request-license-review as a single comment all by itself?

done

sorry for introducing merge conflict, Ed, I found your PR just after merging another :(
should I try to resolve it "inplace" or you prefer to do it in your fork?

**Comment by merks** [comment]
@waynebeaton

Am I doing something wrong for the license check in my build?

https://ci.eclipse.org/oomph/job/simrel/job/simrel-maven-bnd/

It's configured here:

https://git.eclipse.org/c/oomph/org.eclipse.oomph.incubator.git/tree/maven-bnd/pom.xml#n53

**Comment by merks** [comment]
> > Can you please try posting a /request-license-review as a single comment all by itself?
> 
> done
> 
> sorry for introducing merge conflict, Ed, I found your PR just after merging another :( should I try to resolve it "inplace" or you prefer to do it in your fork?

It's no problem at all.  I just quickly force pushed the changes.  😄

**Comment by ruspl-afed** [comment]
Ah, you already resolved the conflict.

There are issues for IP Team:
[p2/orbit/p2.eclipse.plugin/org.apache.lucene.lucene-sandbox/9.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8092)
[p2/orbit/p2.eclipse.plugin/org.mockito.mockito-inline/4.11.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8093)
[p2/orbit/p2.eclipse.plugin/org.apache.lucene.lucene-queries/9.5.0](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/8094)

**Comment by merks** [comment]
FYI, the two Lucene libraries appear to need some manual IP review help, but the Foundation staff are typically awesomely fast...

**Comment by ruspl-afed** [comment]
I was planning to merge this first and then try to rework the rest of dependencies, but now I'm not sure that we will have all in time.

**Comment by merks** [comment]
The review seems stalled. Technically you could proceed with the risk that it might be rejected and you need to rework the dependency. Probably that risk is small. You should not declare a release with these dependencies.

**Comment by waynebeaton** [comment]
Unfortunately, the Lucene JARs all use the same license file and that file is full of licenses that don't apply to most of the JARs... it requires that we manually grind through the license file and compare it against the file list... Since the IP Team this hasn't risen to the top of the IP Team's queue yet, I've approved these requests on their behalf.

AFAIK, the open issues have all be resolved.

**Review by ruspl-afed — APPROVED** [review]
Thank you, @merks and @waynebeaton

**Pull request merged**
