### PR TITLE
add licensecheck.yml

### PR DESCRIPTION
**Pull request by BeckerFrank**

### CODE REVIEW

**Comment by ruspl-afed** [comment]
Looks good, but check is not performed. Perhaps it is blocked by repository settings.

**Comment by BeckerFrank** [comment]
> Looks good, but check is not performed. Perhaps it is blocked by repository settings.

@wimjongman: GitHub Actions / Workflow is new to me. Do you have any idea?

**Comment by ruspl-afed** [comment]
Perhaps the permissions problem. Created an issue for HelpDesk https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2514

**Review by ruspl-afed — APPROVED** [review]
LGTM

**Comment by wimjongman** [comment]
Thanks!

**Pull request merged**
