### PR TITLE
Clean Up: Commons #375

### PR DESCRIPTION
**Pull request by gnl42**
Apply Clean Up rules to Commons packages

Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/375

### CODE REVIEW

**Comment by gnl42** [comment]
Hmm, came across some unwanted "static final" transformations. 
Clean up is cleaning up too much

**Comment by akurtakov** [comment]
What I can see is "public static final" being removed in interfaces as these are implicit which is OK IMHO.

**Review by akurtakov — APPROVED** [review]

**Review by ruspl-afed — APPROVED** [review]
I'm not always happy with combined catch block , but for this code it looks appropriate
LGTM

**Comment by gnl42** [comment]
> What I can see is "public static final" being removed in interfaces as these are implicit which is OK IMHO.

Good catch. Forgot about that, I don't like having constants in interfaces so it's been a long time.

**Pull request merged**
