### PR TITLE
[#111] Need javax.activation and lucene.queries.intervals

### LINKED ISSUE #111: Need javax.activation and lucene.queries.intervals
### I can't install in 4.23 because of javax. activation

<details><summary>requires 'java.package; javax.activation [1.2.0,2.0.0)' but it could not be found</summary>
Cannot complete the install because one or more required items could not be found.
  Software being installed: Mylyn Task-Focused Interface 3.26.0.N20221229-1738 (org.eclipse.mylyn.context_feature.feature.group 3.26.0.N20221229-1738)
  Missing requirement: Old JAXB Runtime 2.3.3.v20221203-1659 (com.sun.xml.bind 2.3.3.v20221203-1659) requires 'java.package; javax.activation [1.2.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Mylyn Commons 3.26.0.N20230320-1407 (org.eclipse.mylyn.commons.notifications.feed 3.26.0.N20230320-1407)
    To: java.package; com.sun.xml.bind 2.3.3
  Cannot satisfy dependency:
    From: Mylyn Context Tasks UI 3.26.0.N20221229-1738 (org.eclipse.mylyn.context.tasks.ui 3.26.0.N20221229-1738)
    To: osgi.bundle; org.eclipse.mylyn.tasks.ui 3.26.0
  Cannot satisfy dependency:
    From: Mylyn Task-Focused Interface 3.26.0.N20221229-1738 (org.eclipse.mylyn.context_feature.feature.group 3.26.0.N20221229-1738)
    To: org.eclipse.equinox.p2.iu; org.eclipse.mylyn.context.tasks.ui [3.26.0.N20221229-1738,3.26.0.N20221229-1738]
  Cannot satisfy dependency:
    From: Mylyn Tasks UI 3.26.0.N20230221-1933 (org.eclipse.mylyn.tasks.ui 3.26.0.N20230221-1933)
    To: osgi.bundle; org.eclipse.mylyn.commons.notifications.feed 3.26.0
</details>

### Can't install in 4.28 because of  requires 'java.package; org.apache.lucene.queries.intervals 0.0.0' but it could not be found

<details><summary> requires 'java.package; org.apache.lucene.queries.intervals 0.0.0' but it could not be found</summary>
Cannot complete the install because one or more required items could not be found.
Software being installed: Mylyn Task-Focused Interface 3.26.0.N20221229-1738 (org.eclipse.mylyn.context_feature.feature.group 3.26.0.N20221229-1738)
Missing requirement: Bundle org.apache.lucene : lucene-queryparser 9.5.0 (org.apache.lucene.lucene-queryparser 9.5.0) requires 'java.package; org.apache.lucene.queries.intervals 0.0.0' but it could not be found
Cannot satisfy dependency:
From: Mylyn Task-Focused Interface 3.26.0.N20221229-1738 (org.eclipse.mylyn.context_feature.feature.group 3.26.0.N20221229-1738)
To: org.eclipse.equinox.p2.iu; org.eclipse.mylyn_feature.feature.group [3.26.0,3.27.0)
Cannot satisfy dependency:
From: Mylyn Task List 3.26.0.N20230416-1636 (org.eclipse.mylyn_feature.feature.group 3.26.0.N20230416-1636)
To: org.eclipse.equinox.p2.iu; org.apache.lucene.lucene-queryparser 9.5.0
</details>

### PR DESCRIPTION
**Pull request by ruspl-afed**
Add required bundles from TP to P2 repository

Fixes #111

### CODE REVIEW

**Comment by ruspl-afed** [comment]
I hope this one will fix the reported issues @wimjongman

**Comment by merks** [comment]
BTW, are you guys aiming/planning to contribute a repo for M2?  I can delay tomorrow's M2 slightly (mid/late morning) if you need some time tomorrow morning.  But I need to plan for that, so if you want or need that, please request that on cross-projects...

**Comment by ruspl-afed** [comment]
> are you guys aiming/planning to contribute a repo for M2?

Yes, we do. There is a [gerrit in progress](https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/201693/2), you are welcome to comment Ed @merks 

> But I need to plan for that, so if you want or need that, please request that on cross-projects...

I still in a hope to finish it today, will let you know

**Review by wimjongman — APPROVED** [review]
+1

**Pull request merged**
