### PR TITLE
Commit Comment Message Template #260

### PR DESCRIPTION
**Pull request by gnl42**
Update commit message template to match project mandate

Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/260

### CODE REVIEW

**Review by ruspl-afed — APPROVED** [review]
LGTM

**Comment by ruspl-afed** [comment]
Thank you @gnl42 !
BTW could you please share your experience regarding configuration of Mylyn GitHub integration? I've got error from GitHub API regarding exceeded amount of API calls from my IP address very quick.

**Comment by gnl42** [comment]
@ruspl-afed You need to use a GitHub token to authenticate

**Comment by BeckerFrank** [comment]
This was fixed with #274

**Pull request closed without merging**
