### PR TITLE
Remove Subclipse integration from distribution #47

### PR DESCRIPTION
**Pull request by ruspl-afed**
Remove org.eclipse.mylyn.subclipse-feature from site 
Remove org.eclipse.mylyn.subclipse-feature and its bundles from reactor

### CODE REVIEW

**Comment by ruspl-afed** [comment]
This looks good for license check. Need your approval @BeckerFrank @wimjongman

**Review by wimjongman — APPROVED** [review]
LGTM. Was the license check failing because of the invalid project ID?

**Comment by BeckerFrank** [comment]
We need to remove the modules from the /org.eclipse.mylyn.versions-parent/pom.xml

**Comment by ruspl-afed** [comment]
> Was the license check failing because of the invalid project ID?

Nope. It was failing because of `org.tigris.subversion` bundles, you can see details [here](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6865)

**Pull request merged**
