### PR TITLE
Ensure that Mylyn update site is complete

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/241

### CODE REVIEW

**Review by ruspl-afed — APPROVED** [review]
LGTM

**Comment by ruspl-afed** [comment]
Does it make validation fully happy Ed @merks ?

**Comment by merks** [comment]
I have test the build locally and I have tested that the SimRel aggregation is successful, so I'm just going to commit this to speed up this process.

**Comment by ruspl-afed** [comment]
> to speed up this process.

Are you running milestone build already Ed @merks ?

**Comment by merks** [comment]
No, not yet.  I was updating this:

https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/203130

**Comment by merks** [comment]
I see a nightly build is running:

https://ci.eclipse.org/mylyn/job/GitHub-mylyn-Orga/job/org.eclipse.mylyn/job/main/110/

And I'm not sure what this build is for/doing:

https://ci.eclipse.org/mylyn/job/GitHub-mylyn-Orga/job/org.eclipse.mylyn/job/prepare_4_0_0_M1/

**Comment by merks** [comment]
I don't think we can run a milestone build while a nightly build is running.  So I think we need to wait for it to finish.   I did kick milestone build off and it seems to have started.  That's not good...

**Comment by merks** [comment]
Ah, I have it like this, in the Jenkinsfile so it aborted the other build:
```
		disableConcurrentBuilds(abortPrevious: true)
```
It will be good to manually kick off a  nightly build afterward so that nightly build is up-to-date....

**Comment by ruspl-afed** [comment]
Yes, after shipping M1 there will be a lot of builds to fix this

**Comment by merks** [comment]
I do a local build and drag the repository folder onto the repository explorer:

image

I use that URI for Mylyn and I invoke Validate Aggregation from the context menu of the root 

image

This Validate Aggregation action is exactly what the validation build does...

**Comment by ruspl-afed** [comment]
Thank you for the explanation, I tried similar things with archived repository but was not sure if I use correct validate action

**Comment by ruspl-afed** [comment]
Milestone is ready, updating Gerrit...

**Comment by merks** [comment]
I was faster.  👅

**Comment by ruspl-afed** [comment]
Thank you so much for your help Ed! 
SimRel can hardly ride without your care.

**Pull request merged**
