### PR TITLE
[#165] Features in Mylyn that aren't in SimRel

### PR DESCRIPTION
**Pull request by ruspl-afed**
Repackage `org.eclipse.egit.mylyn` feature to
`org.eclipse.mylyn.egit.feature`

### CODE REVIEW

**Comment by ruspl-afed** [comment]
@jonahgraham @merks WDYT about `org.eclipse.egit.mylyn` IU rename?

**Comment by jonahgraham** [comment]
IMHO you should rename bundles.

**Comment by ruspl-afed** [comment]
> IMHO you should rename bundles.

do you mean "you should rename bundles as well"?

**Comment by jonahgraham** [comment]
Yes.

**Comment by jonahgraham** [comment]
I think this release should be treated as a new project release and now is the best time to have breaking changes. I.e. Rename and delete everything you can/want. 

FWIW I would call this release 4.0 and plan a 5.0 in the near future.

**Comment by ruspl-afed** [comment]
This is too short timeframe for major release, about two weeks left for everything. The idea of upcoming 3.26.1 is to fix feedback about 3.26.0 in the timeframe of SimRel 2023-06.

Next cycle - yes, we can go with Java 17, removal of everything old, renaming, whatever else.

**Comment by jonahgraham** [comment]
Btw I don't expect my opinion to carry much weight. I am mostly an interested external observer. You folk who have been resurrecting the project have my full support for whatever you deem best.

**Comment by merks** [comment]
I’ll investigate tomorrow if we can rename and use p2.inf to help migrate from the older ID to the new one.

**Comment by merks** [comment]
I agree that renaming the bundles and features will eliminate any confusion in the future.   I can add any p2.inf info for the feature, if possible, after this is committed.

**Comment by ruspl-afed** [comment]
>  after this is committed

I have no idea when it could happen, we have a lot of committers in the project, but it is not so easy to get a review 😎

**Comment by wimjongman** [comment]
I think the bundles should also be renamed. This is the first time we release github inside Mylyn, so no previous history. Let's try to start clean.

**Comment by ruspl-afed** [comment]
> I think the bundles should also be renamed.

@wimjongman  they are, don't they? Or do you see other bundles that should be renamed as well? Please provide more details.

**Review by wimjongman — APPROVED** [review]

**Comment by BeckerFrank** [comment]
> I have no idea when it could happen, we have a lot of committers in the project, but it is not so easy to get a review 😎

Unfortunately, I haven't had much time for Mylyn in the last few days, but I hope to have more time this week.

**Comment by ruspl-afed** [comment]
> Btw I don't expect my opinion to carry much weight. I am mostly an interested external observer. You folk who have been resurrecting the project have my full support for whatever you deem best.

Your opinion [is welcome](https://github.com/eclipse-mylyn/org.eclipse.mylyn/discussions/193) @jonahgraham

**Pull request merged**
