### PR TITLE
Disable integration tests that need mylyn.org #504

### PR DESCRIPTION
**Pull request by BeckerFrank**
Task-Url: https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/504

### CODE REVIEW

**Comment by BeckerFrank** [comment]
@gnl42: We have tests that are running, but also an @Ignore("No CI Server"). Any ideas?

**Comment by gnl42** [comment]
I'll have to take a look when I get home.

How is it that maven reports a successful build when there are failures?

**Comment by BeckerFrank** [comment]
> I'll have to take a look when I get home.
> 
> How is it that maven reports a successful build when there are failures?

The maven build is unstable with 10 failing org.eclipse.mylyn.commons tests.

**Comment by BeckerFrank** [comment]
> I'll have to take a look when I get home.
> How is it that maven reports a successful build when there are failures?

Found that we have the following two lines in the Jenkins File.
```
-Dmaven.test.failure.ignore=true \
-Dmaven.test.error.ignore=true \
```

**Comment by ruspl-afed** [comment]
It seems that we have nothing to contribute for 2024-06 M2, let try to solve this one in the nearest time to have a green build for 2024-06 M3
FYI @merks

**Comment by merks** [comment]
Thank you for keeping me informed.

**Comment by gnl42** [comment]
No errors, but haven't had a chance to look closer at what was run. Tomorrows problem

**Comment by BeckerFrank** [comment]
Actual we skip Network Tests for Jenkins. But Class JenkinsValidationTest did not need the CI Server so we maybe can activate the two unit tests.
Thoughts?

**Comment by gnl42** [comment]
No luck, JenkinsValidationTest needs a Jenkins server to work

**Comment by ruspl-afed** [comment]
Thank you for bringing Mylyn pipeline back to life @gnl42 @BeckerFrank !

**Pull request merged**
