### PR TITLE
Remove guava in wikitext

### PR DESCRIPTION
**Pull request by stephan-herrmann**
+ address core bundle org.eclipse.mylyn.wikitext

https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/521

### CODE REVIEW

**Comment by stephan-herrmann** [comment]
Various strategies applied:
* use basic API like `Character.isWhitespace()` :)
* use streams
* implement minimal replacements
  * XML-escaping (class XML) is inspired from utils we have in o.e.resources as well as jdt.
  * only in GfmIdGenerationStrategy.generateId() a little algo was implemented from scratch
* for the set of `MarkupLanguage` I felt that filtering duplicates should not be necessary if identical language instances are detected using `equals()` and `hashCode()`.
  * this required to adjust one test to force duplicates into a set: same name but different classes

**Comment by stephan-herrmann** [comment]
My goal is to find out if https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1472 could be implemented with wikitext (markdown) and without guava. For that task I don't expect to need any of the \*.ui bundles, as rendering to HTML should be fully sufficient for JDT. In particular no markdown _editing_ is planned.

**Comment by merks** [comment]
This looks promising.

**Comment by gnl42** [comment]
How will this work live with #521?

**Comment by merks** [comment]
> How will this work live with #521?

If I understand correctly, it provides direct implementations that address https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/521#issuecomment-2109504799 for the non-ui parts.

**Comment by stephan-herrmann** [comment]
I admit I found #530 only after submitting this PR :)

So the current PR is much narrower in scope, but succeeds to fully eliminate guava dependency from the core plugin without adding any other dependency.

I'm open to discussions to find the best of all worlds. I'm driven by the fact that JDT needs markdown rendering by September the latest.

**Comment by ruspl-afed** [comment]
@stephan-herrmann thank you for your PR! Perhaps it was my fault to not mention an existing #530 explicitly during [our discussion ](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2429#issuecomment-2180464270)

I would prefer to have #530 merged first, since it was prepared earlier in the scope of #521 and using the same approach as we already have in other parts of Mylyn codebase, and then discuss your change on top of it to reduce the number of required 3rd party libraries. I hope this is fine with you.

> How will this work live with #521?

@gnl42 could you please resolve conflicts for #530 so we can merge it and proceed with further discussion?

**Comment by stephan-herrmann** [comment]
> I would prefer to have #530 merged first, since it was prepared earlier in the scope of #521 and using the same approach as we already have in other parts of Mylyn codebase, and then discuss your change on top of it to reduce the number of required 3rd party libraries. I hope this is fine with you.

Sure, I certainly didn't mean to jump the queue :)

> > How will this work live with #521?
> 
> @gnl42 could you please resolve conflicts for #530 so we can merge it and proceed with further discussion?

If in doubt, some of the more involved changes, that might require a discussion, could perhaps be postponed for later?

**Comment by gnl42** [comment]
#530 has been merged as #565

**Comment by gnl42** [comment]
@stephan-herrmann  Can you recreate your changes against the current main?

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann Can you recreate your changes against the current main?

See new PR #568

**Comment by stephan-herrmann** [comment]
Hopefully #568 will take this to completion.

**Pull request closed without merging**
