### PR TITLE
Fix Task Connectors working set setup

### PR DESCRIPTION
**Pull request by merks**

### CODE REVIEW

**Comment by merks** [comment]
@BeckerFrank 

This fixes a small omission in the pattern.

**Comment by merks** [comment]
@ruspl-afed 

Looks like dash is just failing for no good reason.  😢

**Comment by merks** [comment]
It was empty so removing it is also fine, as long as there are no projects that end up in Other.  :-)

**Comment by merks** [comment]
Yes, I removed it and force pushed the change.

**Review by BeckerFrank — APPROVED** [review]
LGTM

**Pull request merged**
